### ISSUE TITLE
Float imprecision

### ISSUE THREAD

**Issue by Skaft** [Skaft/cd_app#18]
Float numbers are imprecise, as the calculator shows:
0.1 + 0.2 = 0.300000000004
Probably hard to get around, but there it is anyway.

**Comment by daemonanyndel** [comment]
Possibly fixed in float-imprecision pull request #19

**Comment by Skaft** [comment]
Oooh good idea to just round it =) I'll try it out later but looks good. I had a much more complicated approach in mind!
